image: docker:latest
services:
  - docker:dind

stages:
  - build

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

.dockerbuild:
  stage: build
  tags: [ dockerbuild ]

.puppetserver:
  extends: .dockerbuild
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$TAG-$CI_COMMIT_REF_NAME --build-arg "PUPPET_SERVER_VERSION=$PUPPET_SERVER_VERSION" --build-arg "PUPPETDB_TERMINI_VERSION=$PUPPETDB_TERMINI_VERSION" puppetserver
    - docker push $CI_REGISTRY_IMAGE:$TAG-$CI_COMMIT_REF_NAME

puppetserver_53:
  extends: .puppetserver
  variables:
    PUPPET_SERVER_VERSION: '5.3.7'
    PUPPETDB_TERMINI_VERSION: '5.2.7'
    TAG: '5.3'

puppetserver_60:
  extends: .puppetserver
  variables:
    PUPPET_SERVER_VERSION: '6.0.3'
    PUPPETDB_TERMINI_VERSION: '6.0.2'
    TAG: '6.0'

puppetserver_61:
  extends: .puppetserver
  variables:
    PUPPET_SERVER_VERSION: '6.1.0'
    PUPPETDB_TERMINI_VERSION: '6.1.0'
    TAG: '6.1'