version: "2.4"

services:
  haproxy:
    hostname: ${DOMAIN}
    build: haproxy
    volumes:
      - haproxy_ssl:/usr/local/etc/haproxy/ssl/
    networks:
      local:
        aliases:
          - ${DOMAIN}
    ports:
      - 8081:8081
      - 8082:8082
      - 8140:8140
      - 9000:9000
    environment:
      - CA_SERVER=ca.${DOMAIN}
      - PUPPETCA_BACKEND=ca.${DOMAIN}
      - PUPPETDB_BACKEND=db.${DOMAIN}
      - PUPPETSERVER_BACKEND=server.${DOMAIN}
      - PUPPETEXPLORER_BACKEND=explorer.${DOMAIN}

  ca:
    hostname: ca.${DOMAIN}
    build: puppetserver
    volumes:
      - ca_ssl:/etc/puppetlabs/puppet/ssl/
      - ca_data:/opt/puppetlabs/server/data/puppetserver/
    networks:
      local:
        aliases:
          - ca.${DOMAIN}
    environment:
      - CA=enabled
      - CA_NAME=ca.${DOMAIN}
      - CA_SERVER=ca.${DOMAIN}

  server:
    hostname: server.${DOMAIN}
    build: puppetserver
    volumes:
      - server_ssl:/etc/puppetlabs/puppet/ssl/
      - server_data:/opt/puppetlabs/server/data/puppetserver/
      - r10k_env:/etc/puppetlabs/code/environments/
    networks:
      local:
        aliases:
          - server.${DOMAIN}
    environment:
      - CA_SERVER=ca.${DOMAIN}
      - PUPPETDB_SERVER_URL=db.${DOMAIN}:8081

  db:
    hostname: db.${DOMAIN}
    build: puppetdb
    volumes:
      - db_ssl:/etc/puppetlabs/puppet/ssl/
    networks:
      local:
        aliases:
          - db.${DOMAIN}
    environment:
      - CA_SERVER=ca.${DOMAIN}
      - PUPPETDB_USER=puppetdb
      - PUPPETDB_PASSWORD=${PUPPETDB_PASSWORD}

  explorer:
    hostname: explorer.${DOMAIN}
    build: puppetexplorer
    networks:
      local:
        aliases:
          - explorer.${DOMAIN}
    environment:
      - PUPPETDB_SERVER=db.${DOMAIN}

  postgres:
    hostname: postgres.${DOMAIN}
    build: postgres
    environment:
      - POSTGRES_USER=puppetdb
      - POSTGRES_PASSWORD=${PUPPETDB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data/
    networks:
      local:
        aliases:
          - postgres.${DOMAIN}

  nats:
    hostname: nats.${DOMAIN}
    build: nats
    environment:
      - CA_SERVER=ca.${DOMAIN}
    volumes:
      - nats_ssl:/etc/nats/ssl
    networks:
      local:
        aliases:
          - nats.${DOMAIN}
    ports:
      - 4222:4222
    environment:
      - CA_SERVER=ca.${DOMAIN}

  r10k:
    hostname: r10k.${DOMAIN}
    build: r10k
    environment:
      - CA_SERVER=ca.${DOMAIN}
      - R10K_REPO=${R10K_REPO}
      - MCO_R10K_POLICY="policy default deny"
      - NATS=nats.${DOMAIN}:4222
      - PUPPETDB=db.${DOMAIN}
      - PUPPETSERVER=server.${DOMAIN}
    volumes:
      - r10k_env:/etc/puppetlabs/code/environments
      - r10k_cache:/opt/puppetlabs/r10k/cache
      - r10k_ssl:/etc/puppetlabs/puppet/ssl
      - /root/.ssh/id_rsa:/root/.ssh/id_rsa
    networks:
      local:
        aliases:
          - r10k.${DOMAIN}

volumes:
  ca_data:
  ca_ssl:
  db_ssl:
  haproxy_ssl:
  nats_ssl:
  postgres:
  r10k_cache:
  r10k_env:
  r10k_ssl:
  server_data:
  server_ssl:

networks:
   local:
